spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mutsa-db
    username: root
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.SQL: debug
jwt:
  token:
    secret: hihello